export const TEMPLATE_IDS = {
  builder: 'builder',
  government: 'government',
  modern: 'modern',
  traditional: 'traditional',
  lawyer: 'lawyer',
  minimal: 'minimal',
};

/** Default PDF template for new documents */
export const DEFAULT_TEMPLATE_ID = TEMPLATE_IDS.builder;

/**
 * Visually distinct skins — fonts, padding, borders, header bars differ clearly.
 */
export const TEMPLATES = {
  builder: {
    id: 'builder',
    label: { en: 'Builder Style', gu: 'બિલ્ડર સ્ટાઈલ' },
    fonts: { gu: '"Noto Sans Gujarati", "Shruti", "Nirmala UI", sans-serif', en: '"Times New Roman", Times, serif' },
    colors: {
      text: '#000000',
      border: '#000000',
      muted: '#4b5563',
      accent: '#111827',
      headerBg: 'transparent',
      headerText: '#4b5563',
    },
    /** Same layout as Government Style for now (customize later) */
    lineHeight: 1.7,
    pagePadding: '22mm 24mm 20mm 24mm',
    borderWidth: '1px',
    coverBorder: 'none',
    fontSize: '11pt',
    headerBorder: 'none',
    tableHeaderWeight: 700,
    showHeaderRule: false,
    density: 'formal',
  },
  government: {
    id: 'government',
    label: { en: 'Government Style', gu: 'સરકારી સ્ટાઈલ' },
    fonts: { gu: '"Noto Sans Gujarati", "Shruti", "Nirmala UI", sans-serif', en: '"Times New Roman", Times, serif' },
    colors: {
      text: '#000000',
      border: '#000000',
      muted: '#4b5563',
      accent: '#111827',
      headerBg: 'transparent',
      headerText: '#4b5563',
    },
    /** Match AALEKH/govt-sale-deed-format-in-gujarati.pdf leading & margins */
    lineHeight: 1.7,
    pagePadding: '22mm 24mm 20mm 24mm',
    borderWidth: '1px',
    coverBorder: 'none',
    fontSize: '11pt',
    headerBorder: 'none',
    tableHeaderWeight: 700,
    showHeaderRule: false,
    density: 'formal',
  },
  modern: {
    id: 'modern',
    label: { en: 'Modern', gu: 'આધુનિક' },
    fonts: { gu: '"Noto Sans Gujarati", sans-serif', en: 'Georgia, "Times New Roman", serif' },
    colors: {
      text: '#0f172a',
      border: '#64748b',
      muted: '#64748b',
      accent: '#0f172a',
      headerBg: '#f1f5f9',
      headerText: '#0f172a',
    },
    lineHeight: 1.4,
    pagePadding: '16mm 18mm 16mm',
    borderWidth: '1px',
    coverBorder: '1px solid #334155',
    fontSize: '11pt',
    headerBorder: '1px solid #334155',
    tableHeaderWeight: 600,
    showHeaderRule: true,
    density: 'airy',
  },
  traditional: {
    id: 'traditional',
    label: { en: 'Traditional', gu: 'પરંપરાગત' },
    fonts: { gu: '"Noto Sans Gujarati", "Shruti", serif', en: '"Times New Roman", serif' },
    colors: {
      text: '#000000',
      border: '#000000',
      muted: '#222222',
      accent: '#000000',
      headerBg: 'transparent',
      headerText: '#000000',
    },
    lineHeight: 1.45,
    pagePadding: '18mm 20mm 16mm',
    borderWidth: '1px',
    coverBorder: '3px double #000',
    fontSize: '11pt',
    headerBorder: '1px solid #000',
    tableHeaderWeight: 700,
    showHeaderRule: true,
    density: 'formal',
  },
  lawyer: {
    id: 'lawyer',
    label: { en: 'Lawyer Style', gu: 'વકીલ સ્ટાઈલ' },
    fonts: { gu: '"Noto Sans Gujarati", sans-serif', en: '"Times New Roman", serif' },
    colors: {
      text: '#0f172a',
      border: '#0f172a',
      muted: '#334155',
      accent: '#0f172a',
      headerBg: '#e2e8f0',
      headerText: '#0f172a',
    },
    lineHeight: 1.28,
    pagePadding: '10mm 12mm 10mm',
    borderWidth: '1px',
    coverBorder: '1px solid #0f172a',
    fontSize: '9.5pt',
    headerBorder: '1px solid #0f172a',
    tableHeaderWeight: 700,
    showHeaderRule: true,
    density: 'compact',
  },
  minimal: {
    id: 'minimal',
    label: { en: 'Minimal', gu: 'સરળ' },
    fonts: { gu: '"Noto Sans Gujarati", sans-serif', en: 'Georgia, serif' },
    colors: {
      text: '#171717',
      border: '#d4d4d4',
      muted: '#737373',
      accent: '#171717',
      headerBg: 'transparent',
      headerText: '#737373',
    },
    lineHeight: 1.35,
    pagePadding: '20mm 22mm 18mm',
    borderWidth: '1px',
    coverBorder: 'none',
    fontSize: '10.5pt',
    headerBorder: '1px solid #e5e5e5',
    tableHeaderWeight: 600,
    showHeaderRule: false,
    density: 'minimal',
  },
};

/** Sale Deed layouts that use the scanned Gujarat SRO / government bundle */
export const SALE_DEED_GOVT_LAYOUT_TEMPLATES = new Set([
  TEMPLATE_IDS.government,
]);
