import { createEmptyParty } from '../constants/partyTypes';
import { createEmptyPayment } from '../constants/paymentModes';
import { SOFTWARE_VERSION } from '../constants/version';
import { DEFAULT_TEMPLATE_ID } from '../constants/templates';

export function createEmptyGovRecords() {
  return {
    revenue: { extract712No: '', extract712Date: '', remarks: '' },
    mutation: { entryNo: '', date: '', description: '' },
    naPermission: { orderNo: '', date: '', authority: '' },
    tpScheme: { tpNo: '', fpNo: '', remarks: '' },
    propertyCard: { cardNo: '', date: '', issuingAuthority: '' },
    buildingPermission: { permissionNo: '', date: '' },
    developmentPermission: { permissionNo: '', date: '' },
    rera: { registrationNo: '', projectName: '' },
    plotVerification: { orderNo: '', date: '' },
    citySurvey: { citySurveyNo: '', sheetNo: '' },
    extract712: { number: '', date: '' },
    form8A: { khataNo: '', date: '' },
    encumbrance: { certNo: '', date: '' },
    bankNoc: { bankName: '', nocNo: '', date: '' },
    societyNoc: { societyName: '', nocNo: '', date: '' },
    associationCertificate: { name: '', certNo: '', date: '' },
    possessionLetter: { letterNo: '', date: '' },
    completionCertificate: { certNo: '', date: '' },
    occupancyCertificate: { certNo: '', date: '' },
  };
}

export function createEmptyProperty() {
  return {
    propertyType: 'na_land',
    district: '',
    taluka: '',
    subRegistrarOffice: '',
    village: '',
    moje: '',
    subDistrict: '',
    khataNo: '',
    totalAreaHeAreSqm: '',
    soldAreaHeAreSqm: '',
    soldDirection: '',
    aakar: '',
    districtId: '',
    talukaId: '',
    placeId: '',
    sroId: '',
    survey: {
      blockSurveyNo: '',
      oldSurveyNo: '',
      newCitySurveyNo: '',
      tpNo: '',
      fpNo: '',
      tpFpNo: '',
    },
    building: {
      complexName: '',
      siteName: '',
      tower: '',
      wing: '',
      associationName: '',
    },
    unit: {
      floor: '',
      unitNumber: '',
      unitCardNo: '',
      propertyUid: '',
      unitType: 'flat',
    },
    areas: {
      totalPlotArea: '',
      constructionArea: '',
      carpetArea: '',
      builtUpArea: '',
      superBuiltUpArea: '',
      verandaArea: '',
      terraceArea: '',
      parkingArea: '',
      parkingSlots: '',
    },
    permissions: {
      tenureType: 'old_tenure',
      collectorPermissionOrderNo: '',
      collectorPermissionDate: '',
      isBuiltUp: false,
      naOrderNo: '',
      naOrderDate: '',
      plotValidationOrderNo: '',
      plotValidationDate: '',
      constructionPermissionNo: '',
      constructionPermissionDate: '',
      reraNumber: '',
      gpaDetails: '',
      banakhatDate: '',
      hasMortgage: false,
      mortgageDetails: '',
      hasGpa: false,
    },
    utilities: { electricity: '', water: '', drainage: '' },
    parking: { type: '', slots: '', area: '' },
    boundaries: { east: '', west: '', north: '', south: '' },
    coordinates: { latitude: '', longitude: '' },
    ownership: { nature: 'absolute', remarks: '' },
    jantriValue: '',
    postalAddress: '',
    photos: { sitePhoto: '', boundaryPhoto: '', structurePhoto: '' },
    govRecords: createEmptyGovRecords(),
    // flat aliases kept for wizard compatibility during migration
    blockSurveyNo: '',
    oldSurveyNo: '',
    newCitySurveyNo: '',
    tpFpNo: '',
    tenureType: 'old_tenure',
    collectorPermissionOrderNo: '',
    collectorPermissionDate: '',
    isBuiltUp: false,
    naOrderNo: '',
    naOrderDate: '',
    totalPlotArea: '',
    constructionArea: '',
    carpetArea: '',
    complexName: '',
    siteName: '',
    tower: '',
    floor: '',
    unitNumber: '',
    unitCardNo: '',
    unitType: 'flat',
    verandaArea: '',
    reraNumber: '',
    latitude: '',
    longitude: '',
    parkingType: '',
    parkingSlots: '',
    parkingArea: '',
    plotValidationOrderNo: '',
    plotValidationDate: '',
    constructionPermissionNo: '',
    constructionPermissionDate: '',
    banakhatDate: '',
    gpaDetails: '',
    associationName: '',
    revenueRecords: {
      extract712No: '',
      extract712Date: '',
      khata8ANo: '',
      mutationEntryNo: '',
      mutationDate: '',
      propertyCardNo: '',
      encumbranceCertNo: '',
      encumbranceCertDate: '',
    },
  };
}

export function createEmptyWitness() {
  return {
    name: '',
    age: '',
    occupation: '',
    address: '',
    pan: '',
    aadhaar: '',
    mobile: '',
    photo: '',
    signature: '',
    thumbImpression: '',
  };
}

export function createEmptyDocument(overrides = {}) {
  const now = new Date().toISOString();
  return {
    id: overrides.id || `doc_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`,
    documentType: 'sale_deed_flat',
    templateId: DEFAULT_TEMPLATE_ID,
    locale: 'gu',
    status: 'draft',
    version: SOFTWARE_VERSION,
    createdAt: now,
    updatedAt: now,
    generatedAt: null,
    documentNumber: '',
    registrationDate: '',
    parties: {
      sellers: [createEmptyParty('company')],
      buyers: [createEmptyParty('individual')],
      confirmers: [],
    },
    property: createEmptyProperty(),
    titleHistory: [{ entryNo: '', date: '', description: '' }],
    transaction: {
      totalSaleAmount: '',
      paymentMode: 'RTGS',
      payments: [createEmptyPayment('RTGS')],
      stampDutyReceiptNo: '',
      stampDutyAmount: '',
      registrationFeeReceiptNo: '',
      registrationFeeAmount: '',
      tdsChallanNo: '',
      tdsForm26QB: '',
      tdsPaidDate: '',
      // type-specific
      giftConsideration: '',
      leaseTermMonths: '',
      monthlyRent: '',
      securityDeposit: '',
      loanAmount: '',
      interestRate: '',
    },
    compliance: {
      sellerIdVerified: false,
      buyerIdVerified: false,
      propertyCardVerified: false,
      revenueRecordsVerified: false,
      naOrderVerified: false,
      stampDutyPaid: false,
      registrationFeePaid: false,
      tdsComplied: false,
      witnessesPresent: false,
      photosAttached: false,
    },
    witnesses: [createEmptyWitness(), createEmptyWitness()],
    identifier: {
      name: '',
      aadhaar: '',
      mobile: '',
      relation: 'Advocate / Presenter',
      preparedBy: '',
    },
    branding: {
      orgName: 'DM Associates',
      orgTagline: 'Legal Document Generator',
      mobile: '',
      logo: '',
    },
    execution: {
      executionDate: '',
      executionPlace: '',
      possessionDate: '',
      possessionType: 'immediate',
      garviApplicationNo: '',
      documentSerialNo: '',
      garviAppointmentDate: '',
      garviAppointmentSlot: '',
      presentingPartyMobile: '',
      presentingPartyEmail: '',
    },
    ...overrides,
  };
}
